### ISSUE TITLE
Coord offset feature suggestion

### ISSUE THREAD

**Issue by june012006** [TROG111/SatNav#2]
A potentially useful feature to add would be to provide a configurable offset for the coords stored in the databank.   The reason is, given sufficient braking power,  Dimencia's HUD autopilot is very, very precise.   Going to the markets on Alioth, the autopilot will place you on top of the antenna on the central building, consistently.   An offset would allow landing on the pad, instead of the center building.

**Comment by TROG111** [comment]
The alioth locations provided are examples. They are there for you to 
replace with your own preferred landing location. It would never be 
possible to provide locations at the markets than can be guaranteed clear 
of other ships. Sorry, but you will need to update the lications provided 
as suits you. Simply land, copy your current location coordinates from the 
map and paste then into the lua code in the satnav.

Stephen

**Comment by TROG111** [comment]
Closed as not needed
